# bitbucket-pipelines.yml - Bitbucket Pipelines configuration
# Copyright (C) 2016-2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.

# See <https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html>
# for details.
---
definitions:
  caches:
    openj9: /root/javasharedresources
  steps:
    - step: &test
        name: Test
        image: adoptopenjdk/maven-openjdk8-openj9:latest
        caches:
          - maven
          - openj9
        script:
          - export OPENJ9_JAVA_OPTIONS="-Xtune:virtualized"
          - export MAVEN_OPTS="-Xgcpolicy:optthruput -Xshareclasses"
          - mvn -B -s etc/settings.xml ${OSSRH_USERNAME+-P ossrh} test
    - step: &deploy
        name: Deploy
        image: adoptopenjdk/maven-openjdk8-openj9:latest
        caches:
          - maven
          - openj9
        script:
          - apt-get update --quiet=2
          - apt-get install --quiet=2 --no-install-recommends gpg gpg-agent
          - export GNUPGHOME=`mktemp -d`
          - sh etc/gpginit.sh
          - export OPENJ9_JAVA_OPTIONS="-Xtune:virtualized"
          - export MAVEN_OPTS="-Xgcpolicy:optthruput -Xshareclasses"
          - mvn -B -s etc/settings.xml ${OSSRH_USERNAME+-P ossrh} -Dmaven.deploy.skip deploy
        artifacts:
          - target/*
    - step: &upload-bitbucket
        name: Upload to Bitbucket Cloud
        script:
          - sh etc/upload.sh target/*.nbm target/*.nbm.asc
pipelines:
  branches:
    master:
      - step: *test
    deployment/test:
      - step:
          <<: *deploy
          deployment: test
      - step: *upload-bitbucket
    deployment/staging:
      - step:
          <<: *deploy
          deployment: staging
      - step: *upload-bitbucket
