# bitbucket-pipelines.yml - Bitbucket Pipelines configuration
# Copyright (C) 2016-2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.

# See <https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html>
# for details.
---
definitions:
  caches:
    openj9: /root/javasharedresources
  steps:
    - step: &test
        name: Test
        caches:
          - maven
          - openj9
        script:
          - export MAVEN_OPTS="-Xgcpolicy:optthruput -Xshareclasses"
          - mvn -B -s etc/settings.xml test
image: adoptopenjdk/maven-openjdk8-openj9:latest
pipelines:
  default:
    - step: *test
  branches:
    production:
      - step:
          deployment: production
          caches:
            - maven
          script:
            - export GNUPGHOME=`mktemp -d`
            - sh etc/gpginit.sh
            - export MAVEN_OPTS="-Xquickstart"
            - mvn -B -s etc/settings.xml ${OSSRHUSERNAME+-P ossrh} -Dmaven.deploy.skip deploy
            - sh etc/upload.sh target/*.nbm target/*.nbm.asc
  bookmarks:
    staging:
      - step:
          deployment: staging
          caches:
            - maven
          script:
            - export GNUPGHOME=`mktemp -d`
            - sh etc/gpginit.sh
            - export MAVEN_OPTS="-Xquickstart"
            - mvn -B -s etc/settings.xml ${OSSRHUSERNAME+-P ossrh} -Dmaven.deploy.skip deploy
            - sh etc/upload.sh target/*.nbm target/*.nbm.asc
    master:
      - step:
          deployment: test
          caches:
            - maven
          script:
            - export GNUPGHOME=`mktemp -d`
            - sh etc/gpginit.sh
            - export MAVEN_OPTS="-Xquickstart"
            - mvn -B -s etc/settings.xml ${OSSRHUSERNAME+-P ossrh} install
          artifacts:
            - target/*
